# Generated by Django 4.2.24 on 2025-09-29 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CancerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FactorMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geographic_level', models.CharField(choices=[('State', 'State'), ('County', 'County')], max_length=10)),
                ('state', models.CharField(max_length=100)),
                ('statefp', models.CharField(blank=True, max_length=2, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('countyfp', models.CharField(blank=True, max_length=5, null=True)),
                ('factor_value', models.FloatField(blank=True, null=True)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.factor')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.gender')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.race')),
            ],
        ),
        migrations.CreateModel(
            name='CancerIncidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geographic_level', models.CharField(choices=[('State', 'State'), ('County', 'County')], max_length=10)),
                ('state', models.CharField(max_length=100)),
                ('statefp', models.CharField(blank=True, max_length=2, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('countyfp', models.CharField(blank=True, max_length=5, null=True)),
                ('incidence_rate', models.FloatField(blank=True, null=True)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('cancer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.cancertype')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.gender')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.race')),
            ],
        ),
    ]
