# Generated by Django 4.2.23 on 2025-09-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=100)),
                ('cancer_rate', models.FloatField()),
                ('eso_rate', models.FloatField(blank=True, null=True)),
                ('kidney_rate', models.FloatField(blank=True, null=True)),
                ('liver_rate', models.FloatField(blank=True, null=True)),
                ('lung_rate', models.FloatField(blank=True, null=True)),
                ('pancreatic_rate', models.FloatField(blank=True, null=True)),
                ('prostate_rate', models.FloatField(blank=True, null=True)),
                ('skin_rate', models.FloatField(blank=True, null=True)),
                ('drinking', models.FloatField(blank=True, null=True)),
                ('obesity', models.FloatField(blank=True, null=True)),
                ('diabetes', models.FloatField(blank=True, null=True)),
                ('heart_disease', models.FloatField(blank=True, null=True)),
                ('poverty', models.FloatField(blank=True, null=True)),
                ('noHealthIns', models.FloatField(blank=True, null=True)),
                ('smoking', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('cancer_rate', models.FloatField()),
                ('eso_rate', models.FloatField(blank=True, null=True)),
                ('kidney_rate', models.FloatField(blank=True, null=True)),
                ('liver_rate', models.FloatField(blank=True, null=True)),
                ('lung_rate', models.FloatField(blank=True, null=True)),
                ('pancreatic_rate', models.FloatField(blank=True, null=True)),
                ('prostate_rate', models.FloatField(blank=True, null=True)),
                ('skin_rate', models.FloatField(blank=True, null=True)),
                ('drinking', models.FloatField(blank=True, null=True)),
                ('obesity', models.FloatField(blank=True, null=True)),
                ('diabetes', models.FloatField(blank=True, null=True)),
                ('heart_disease', models.FloatField(blank=True, null=True)),
                ('poverty', models.FloatField(blank=True, null=True)),
                ('noHealthIns', models.FloatField(blank=True, null=True)),
                ('smoking', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
