# Generated by Django 4.2.24 on 2025-09-27 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactorMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Environment', 'Environment'), ('Health', 'Health'), ('Lifestyle', 'Lifestyle')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips_code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips_code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counties', to='dashboard.state')),
            ],
        ),
        migrations.CreateModel(
            name='FactorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('value', models.FloatField()),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.county')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.factormetric')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.state')),
            ],
            options={
                'indexes': [models.Index(fields=['metric', 'state', 'county', 'year'], name='dashboard_f_metric__59f96f_idx'), models.Index(fields=['metric', 'state', 'year'], name='dashboard_f_metric__eac6eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='CancerIncidenceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('cancer_type', models.CharField(choices=[('Pancreatic', 'Pancreatic'), ('Skin', 'Skin'), ('Lung', 'Lung'), ('Liver', 'Liver'), ('Breast', 'Breast'), ('Kidney', 'Kidney'), ('Prostate', 'Prostate'), ('Esophageal', 'Esophageal')], max_length=50)),
                ('incidence_rate', models.FloatField()),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('race', models.CharField(blank=True, choices=[('White (includes Hispanic)', 'White'), ('Black (includes Hispanic)', 'Black'), ('Asian/Pacific Islander (includes Hispanic)', 'Asian'), ('Hispanic (all races)', 'Hispanic')], max_length=50, null=True)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.county')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.state')),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'county', 'year', 'cancer_type'], name='dashboard_c_state_i_fd017b_idx'), models.Index(fields=['state', 'year', 'cancer_type'], name='dashboard_c_state_i_7439de_idx'), models.Index(fields=['state', 'county', 'year', 'cancer_type', 'sex'], name='dashboard_c_state_i_255a71_idx'), models.Index(fields=['state', 'year', 'cancer_type', 'sex'], name='dashboard_c_state_i_ddc2d6_idx'), models.Index(fields=['state', 'county', 'year', 'cancer_type', 'race'], name='dashboard_c_state_i_936040_idx'), models.Index(fields=['state', 'year', 'cancer_type', 'race'], name='dashboard_c_state_i_2c4377_idx')],
            },
        ),
    ]
