# Generated by Django 4.2.24 on 2025-11-16 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalRecordAgg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tumor_Sample_Barcode', models.CharField(max_length=64)),
                ('Hugo_Symbol', models.JSONField(default=list)),
                ('HGVSc', models.JSONField(default=list)),
                ('Variant_Classification', models.JSONField(default=list)),
                ('TSS', models.CharField(blank=True, max_length=16)),
                ('bcr_patient_barcode', models.CharField(blank=True, max_length=64)),
                ('Source_Site', models.CharField(blank=True, max_length=128)),
                ('Study_Name', models.CharField(blank=True, max_length=128)),
                ('ajcc_pathologic_stage', models.CharField(blank=True, max_length=64)),
                ('age_at_diagnosis', models.IntegerField(blank=True, null=True)),
                ('year_of_diagnosis', models.IntegerField(blank=True, null=True)),
                ('race', models.CharField(blank=True, max_length=64)),
                ('gender', models.CharField(blank=True, max_length=32)),
                ('ethnicity', models.CharField(blank=True, max_length=64)),
                ('vital_status', models.CharField(blank=True, max_length=32)),
                ('treatments_pharmaceutical_treatment_or_therapy', models.CharField(blank=True, max_length=128)),
                ('treatments_radiation_treatment_or_therapy', models.CharField(blank=True, max_length=128)),
                ('cancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.cancertype')),
            ],
        ),
    ]
