# Generated by Django 4.2.24 on 2026-01-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_totalrecordagg'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalrecordagg',
            name='Amino_acids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='COSMIC',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='Chromosome',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='Codons',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='End_Position',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='Entrez_Gene_Id',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='Exon_Number',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='HGVSp_Short',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='IMPACT',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='PolyPhen',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='Protein_position',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='Reference_Allele',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='SIFT',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='Start_Position',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='Transcript_ID',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='Tumor_Seq_Allele2',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='Variant_Type',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='bcr_patient_uuid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='case_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='days_to_death',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='days_to_last_followup',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='histological_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='history_of_neoadjuvant_treatment',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='hotspot',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='icd_10',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='icd_o_3_histology',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='icd_o_3_site',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='patient_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='person_neoplasm_cancer_status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='primary_therapy_outcome_success',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='project',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='stage_event_clinical_stage',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='stage_event_system_version',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='stage_event_tnm_categories',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='t_alt_count',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='t_depth',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='tissue_source_site',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='totalrecordagg',
            name='tumor_tissue_site',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='totalrecordagg',
            name='ajcc_pathologic_stage',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='totalrecordagg',
            name='bcr_patient_barcode',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='totalrecordagg',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='totalrecordagg',
            name='gender',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='totalrecordagg',
            name='race',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='totalrecordagg',
            name='treatments_pharmaceutical_treatment_or_therapy',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='totalrecordagg',
            name='treatments_radiation_treatment_or_therapy',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='totalrecordagg',
            name='vital_status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
