# Generated by Django 4.2.24 on 2026-01-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_totalrecordagg_amino_acids_totalrecordagg_cosmic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalrecordagg',
            name='Source_Site',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='totalrecordagg',
            name='Study_Name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='totalrecordagg',
            name='TSS',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
