# Generated by Django 4.2.24 on 2026-01-12 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_totalrecordagg_source_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkNodeMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_index', models.IntegerField()),
                ('Tumor_Sample_Barcode', models.CharField(blank=True, max_length=64)),
                ('age_at_initial_pathologic_diagnosis', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=32)),
                ('vital_status', models.CharField(blank=True, max_length=32)),
                ('race_list', models.CharField(blank=True, max_length=128)),
                ('ethnicity', models.CharField(blank=True, max_length=128)),
                ('n_events', models.IntegerField(blank=True, null=True)),
                ('n_genes', models.IntegerField(blank=True, null=True)),
                ('event_ids', models.JSONField(default=list)),
                ('genes', models.JSONField(default=list)),
                ('cancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.cancertype')),
            ],
            options={
                'unique_together': {('cancer', 'node_index')},
            },
        ),
    ]
