# Generated by Django 4.2.24 on 2026-01-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_networknodemeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networknodemeta',
            name='event_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='networknodemeta',
            name='genes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
